### ISSUE TITLE
"Run in Browser" link 404

### ISSUE THREAD

**Issue by Gama11** [JoeCreates/MacroTweenDemo#1]
The link from the readme just gives me a 404 (which makes sense, as there's no gh-pages branch?).

https://joecreates.github.io/MacroTweenDemo/index.html

**Comment by Tw1ddle** [comment]
Hi Gama, I've just fixed that and noted down controls in the readme - https://github.com/JoeCreates/MacroTweenDemo/blob/master/README.md

Disclaimer, this isn't battle-tested code 😛

**Comment by Gama11** [comment]
I don't really plan on using it for anything atm, was mostly curious about the demo. :)

Nice demo btw!
